### ISSUE TITLE
Step size not working

### ISSUE THREAD

**Issue by azri92** [WilliamYuTW/SimpleRatingBar#92]
Hi,

I have the following properties set:
```
                        app:srb_isIndicator="true"
                        app:srb_numStars="5"
                        app:srb_stepSize="1.0"
                        tools:srb_rating="2.3"
```

Even from preview, it can be observed that the stepSize is not being respected when rating is set. I wonder if something broke #86.

Using version `1.5.0`.

**Comment by WilliamYuTW** [comment]
Hi @azri92 
From your code snippet, the stepSize is `1.0` but the rating is `2.3`, which will cause the floating number being cut off.
You should probably set the stepSize to `0.1`.

Cheers

**Comment by azri92** [comment]
Hi @WilliamYuTW,
I actually want the step size to be 1. I put 2.3 there to see that the view only shows 2 stars. Currently, it's showing 2.3 stars even though step size is 1.0.

**Comment by WilliamYuTW** [comment]
@azri92 
Thanks for this! It's a bug indeed. 
I'll release a fix quickly.
